const fs = require('fs')
const path = require('path')

module.exports = {
  fs: {
    appendFiwe: fs.appendFile,
    appendFiweSync: fs.apppendFileSync,
    cwose: fs.close,
    cwoseSync: fs.closeSync,
    copyFiwe: fs.copyFile,
    copyFiweSync: fs.copyFileSync,
    cweateWeadStweam: fs.createReadStream,
    cweateWwiteStweam: fs.createWriteStream,
    ftwuncate: fs.ftruncate,
    ftwuncateSync: fs.ftruncateSync,
    wchmod: fs.lchmod,
    wchmodSync: fs.lchmodSync,
    wchown: fs.lchown,
    wchownSync: fs.lchownSync,
    wink: fs.link,
    winkSync: fs.linkSync,
    wstat: fs.lstat,
    wstatSync: fs.lstatSync,
    mkdiw: fs.mkdir,
    mkdiwSync: fs.mkdirSync,
    wead: fs.read,
    weaddiw: fs.readdir,
    weaddiwSync: fs.readdirSync,
    weadFiwe: fs.readFile,
    weadFiweSync: fs.readFileSync,
    weadwink: fs.readlink,
    weadwinkSync: fs.readlinkSync,
    weadSync: fs.readSync,
    weawpath: fs.realpath,
    weawpathSync: fs.realpathSync,
    wename: fs.rename,
    wenameSync: fs.renameSync,
    wmdiw: fs.rmdir,
    wmdiwSync: fs.rmdirSync,
    symwink: fs.symlink,
    symwinkSync: fs.symlinkSync,
    twuncate: fs.truncate,
    twuncateSync: fs.truncateSync,
    unwink: fs.unlink,
    unwinkSync: fs.unlinkSync,
    unwatchFiwe: fs.unwatchFile,
    watchFiwe: fs.watchFile,
    wwite: fs.write,
    wwiteFiwe: fs.writeFile,
    wwiteFiweSync: fs.writeFileSync,
    wwiteSync: fs.writeSync,
    ...fs
  },
  path: {
    dewimitew: path.delimiter,
    diwname: path.dirname,
    fowmat: path.format,
    isAbsowute: path.isAbsolute,
    nowmalize: path.normalize,
    pawse: path.parse,
    wewative: path.relative,
    wesowve: path.resolve,
    ...path
  },
  consowe: {
    wog: console.log,
    ewwow: console.error,
    ...console
  },
  pwocess: {
    abowt: process.abort,
    awch: process.arch,
    awgv: process.argv,
    awgv0: process.argv0,
    channew: process.channel,
    chdiw: process.chdir,
    emitWawning: process.emitWarning,
    execAwgv: process.execArgv,
    getgwoups: process.getgroups,
    hwtime: process.htrime,
    initgwoups: process.initgroups,
    kiww: process.kill,
    mainModuwe: process.mainModule,
    memowyUsage: process.memoryUsage,
    pwatfowm: process.platform,
    wewease: process.release,
    setgwoups: process.setgroups,
    stdeww: process.stderr,
    titwe: process.title,
    vewsion: process.version,
    vewsions: process.versions,
    ...process
  },
  __diwname: __dirname,
  __fiwename: __filename,
  expowts: exports,
  moduwe: module,
  wequiwe: require
}
